version: "3.9"
services:
  fe:
    build: ./packages/fe
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - be
    links:
      - be
  be:
    build: ./packages/be
    container_name: backend
    ports:
      - "3001:3001"